services:
  app_server:
    image: localhost:5000/app_server
    build: ./app_server
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 8
      placement:
        max_replicas_per_node: 4

  app_haproxy:
    image: localhost:5000/app_lb
    build: ./app_lb
    ports:
      - "9000:9000"
    networks:
      - outside
    privileged: true
    volumes:
      - ./app_haproxy:/usr/local/etc/haproxy:ro
    deploy:
      placement:
        constraints: [ node.labels.haproxy == true ]

networks:
  outside:
    name: host
    external: true