#version: "3.8"
#services:
#  # app_server1:
#  #   image: st108vm101.rtb-lab.pl/app_server
#  #   build: ./app_server
#  #   # ports:
#  #   #   - "8000:8000"
#  #   deploy:
#  #     mode: replicated
#  #     replicas: 1
#  #     placement:
#  #       max_replicas_per_node: 2
#  #       constraints:
#  #         - node.labels.slow != true
#  #         - node.labels.haproxy != true
#
#  # app_server2:
#  #   image: st108vm101.rtb-lab.pl/app_server
#  #   build: ./app_server
#  #   # ports:
#  #   #   - "8000:8000"
#  #   deploy:
#  #     mode: replicated
#  #     replicas: 1
#  #     placement:
#  #       max_replicas_per_node: 2
#  #       constraints:
#  #         - node.labels.haproxy != true
#  #         - node.labels.slow == true
#
#  app_server2: &app-server
#    image: st108vm101.rtb-lab.pl/app_server
#    networks:
#      - redis_cluster_net
#    deploy:
#      placement:
#        constraints:
#          - node.labels.s02 == true
#
#  app_server3:
#    <<: *app-server
#    deploy:
#      placement:
#        constraints:
#          - node.labels.s03 == true
#
#  app_server4:
#    image: st108vm101.rtb-lab.pl/app_server
#    deploy:
#      placement:
#        constraints:
#          - node.labels.s04 == true
#
#  app_server5:
#    image: st108vm101.rtb-lab.pl/app_server
#    deploy:
#      placement:
#        constraints:
#          - node.labels.s05 == true
#
#  app_server6:
#    image: st108vm101.rtb-lab.pl/app_server
#    deploy:
#      placement:
#        constraints:
#          - node.labels.s06 == true
#
#  app_haproxy:
#    image: st108vm101.rtb-lab.pl/app_haproxy
#    build: ./app_haproxy
#    ports:
#      - "9000:9000"
#      - "10000:10000"
#    # network_mode: host
#    # networks:
#    #   - outside
#    privileged: true
#    user: 0:0
#    volumes:
#      - ./app_haproxy:/usr/local/etc/haproxy:ro
#    deploy:
#      placement:
#        constraints: [ node.labels.haproxy == true ]
#
## networks:
##   outside:
##     name: host
##     external: true

version: "3.8"
services:
  app_server:
    image: st108vm101.rtb-lab.pl/app_server
    build: ./app_server
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 5
      placement:
        max_replicas_per_node: 2
        constraints: 
          - node.labels.haproxy != true



  app_haproxy:
    image: st108vm101.rtb-lab.pl/app_haproxy
    build: app_haproxy
    ports:
      - "9000:9000"
      - "10000:10000"
    # network_mode: host
    # networks:
    #   - outside
    # privileged: true
    # user: 0:0
    # volumes:
    #   - ./app_haproxy:/usr/local/etc/haproxy:ro
    deploy:
      placement:
        constraints: [ node.labels.haproxy == true ]

  redis_1:
    image: 'redis:latest'
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.2
    deploy:
      placement:
        constraints: 
          - node.labels.s07 == true

# networks:
#   outside:
    # name: host
    # external: true