version: "3.8"

services:
  app_server:
    image: st108vm101.rtb-lab.pl/app_server
    build: ./app_server
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 8
      placement:
        max_replicas_per_node: 4

  app_haproxy:
    image: localhost/app_haproxy
    build: ./app_haproxy
    ports:
      - "9000:9000"
      - "10000:10000"
    networks:
      - outside
    privileged: true
    volumes:
      - ./app_haproxy:/usr/local/etc/haproxy:ro
    deploy:
      placement:
        constraints: [ node.labels.haproxy == true ]

networks:
  outside:
    name: host
    external: true
